// Generated by gencpp from file pkg_task2/temp1.msg
// DO NOT EDIT!


#ifndef PKG_TASK2_MESSAGE_TEMP1_H
#define PKG_TASK2_MESSAGE_TEMP1_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_task2
{
template <class ContainerAllocator>
struct temp1_
{
  typedef temp1_<ContainerAllocator> Type;

  temp1_()
    : a()
    , b()  {
    }
  temp1_(const ContainerAllocator& _alloc)
    : a(_alloc)
    , b(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _a_type;
  _a_type a;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::pkg_task2::temp1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_task2::temp1_<ContainerAllocator> const> ConstPtr;

}; // struct temp1_

typedef ::pkg_task2::temp1_<std::allocator<void> > temp1;

typedef boost::shared_ptr< ::pkg_task2::temp1 > temp1Ptr;
typedef boost::shared_ptr< ::pkg_task2::temp1 const> temp1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_task2::temp1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_task2::temp1_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pkg_task2::temp1_<ContainerAllocator1> & lhs, const ::pkg_task2::temp1_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pkg_task2::temp1_<ContainerAllocator1> & lhs, const ::pkg_task2::temp1_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pkg_task2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pkg_task2::temp1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_task2::temp1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_task2::temp1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_task2::temp1_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_task2::temp1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_task2::temp1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_task2::temp1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efc98bdd092d58ce0c705b4bd69d178c";
  }

  static const char* value(const ::pkg_task2::temp1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefc98bdd092d58ceULL;
  static const uint64_t static_value2 = 0x0c705b4bd69d178cULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_task2::temp1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_task2/temp1";
  }

  static const char* value(const ::pkg_task2::temp1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_task2::temp1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string a\n"
"string b\n"
;
  }

  static const char* value(const ::pkg_task2::temp1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_task2::temp1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct temp1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_task2::temp1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_task2::temp1_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_TASK2_MESSAGE_TEMP1_H
